name: Push Stage version to DockerHub

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Шаг 1: Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Обрезка SHA коммита до 7 символов
      - name: Cut commit sha
        id: cut
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Шаг 3: Логин в Docker Hub
      - name: Log into DockerHUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCHUB_USERNAME }}
          password: ${{ secrets.DOCHUB_TOKEN }}

      # Шаг 4: Настройка Docker Buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Шаг 5: Сборка и отправка Docker-образа
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ vars.DOCHUB_USERNAME }}/var_keeper:${{ steps.cut.outputs.sha_short }}
