name: Unit Tests Workflow

on:
  push:
    branches-ignore:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout репозитория
      - name: Checkout
        uses: actions/checkout@v4

      # Шаг 2: Запуск модульных тестов
      - name: Run Unit Tests
        run: echo "Unit Tests PASS"
