name: CI Pipeline

on:
  push:
    branches: [ "test", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - run: npm install
    - run: npm run build
    
  test:
    needs: build
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    - run: npm test
